server:
  port: 9191

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/micro?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: PAYMENT-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Alphabet
keycloak:
  realm: Alphabet
  auth-server-url: http://localhost:8080/auth
  resource: springboot-keytest
  public-client: true
  principal-attribute: preferred_username
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /payment/*
#logging:
#  file:
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
