server:
  port: 9192


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: jdbc:mysql://localhost:3306/micro
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: ORDER-SERVICE
#  cloud:
#    config:
#      uri:
#        - http://localhost:9196
#logging:
#  file:
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost


